import type { Metadata } from 'next'
import './globals.css'
import { twMerge } from 'tailwind-merge'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={twMerge('font-sans bg-[#fbf7ff]')}>
                {children}
            </body>
        </html>
    )
}
